### PR TITLE
feat(App.tsx, Modal.tsx): markAsCompleted, random id, autofocus

### PR DESCRIPTION
**Pull request by ismalzikri**
an additional feature of the mark as completed

add generate a random id when adding an item todos

add autofocus at modal add item

### CODE REVIEW

**Comment by mhaidarhanif** [comment]
Please also deploy the app to somewhere, like Vercel or Netlify. The PR will have a preview deployment.

Another way is to provide a screenshot or screencast of the specific changes for the UI:

- Mark as completed
- Add new todo with nanoid

**Comment by ismalzikri** [comment]
> Please also deploy the app somewhere, like Vercel or Netlify. The PR will have a preview deployment.
> 
> Another way is to provide a screenshot or screencast of the specific changes for the UI:
> 
> * Mark as completed
> * Add new todo with nanoid

hi @mhaidarhanif , I'm done with the requested issue, but I have to wait to deploy to the server until these changes are approved, and then next time you'll see the live demo when this project has any changes.

Screenshot 2023-05-11 at 09 14 03
Screenshot 2023-05-11 at 09 15 10
Screenshot 2023-05-11 at 09 15 40

**Comment by mhaidarhanif** [comment]
Actually, you can still deploy it to Vercel/Netlify just fine without worrying this PR is approved and merged first.

Imagine that someday it's part of the test to deploy early.

But alright then, just merge it for now.

**Review by mhaidarhanif — APPROVED** [review]
Approved

**Comment by mhaidarhanif** [comment]
Okay then, it's now more than ready to deploy.

And to remind again: It's totally fine to deploy even in the initial 5 minutes of development.

**Comment by ismalzikri** [comment]
> Okay then, it's now more than ready to deploy.
> 
> And to remind again: It's totally fine to deploy even in the initial 5 minutes of development.

working on it...

https://zikri-dailist.netlify.app/

**Pull request merged**
